###########--VERSION--##############
version: '3.5'

###########--SERVICIOS--##############
services:

###########--SOCKET--##############
 socket:
  container_name: socket
  restart: always
  build:
    context: ./socket/
    dockerfile: Dockerfile
    args:
      SSHPASS: ${BUS_PASS}
      USER: ${BUS_USER}
      SERVER: ${BUS_SERVER}
  env_file:
    - .env
  ports:
    - "3000:5000"
  volumes:
    - ./socket:/app
  
 server:
    container_name: server
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SOCKET_HOST=socket
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - "db"
      - "socket"

###########--MARIADB--##############
 db:
    image: postgres:10.5
    container_name: postgres
    ports:
      - '5432:5432'
    env_file:
      - db.env
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/'
        
   