version: '3.5'

services:

  socket:
    container_name: socket
    restart: always
    build:
      context: ./socket/
      dockerfile: Dockerfile
      args:
        SSHPASS: ${BUS_PASS}
        USER: ${BUS_USER}
        SERVER: ${BUS_SERVER}
    env_file:
      - .env
    ports:
      - "3000:5000"
    volumes:
      - ./socket:/app
   
#  postgres:
#    container_name: postgres
    # image: docker.io/bitnami/postgresql:11
    # volumes:
    #     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
    #     - "3000:5432"
    # environment:
    #     - POSTGRESQL_USER=postgres
    #     - POSTGRESQL_DATABASE=tiendita
    #     - ALLOW_EMPTY_PASSWORD=yes
    #     - POSTGRESQL_PASSWORD=postgres
   