version: '3.5'

services:

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - db.env
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/'

  server:
    container_name: server
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SOCKET_HOST=socket
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - "db"
      - "socket"

  socket:
    container_name: socket
    restart: always
    build:
      context: ./socket/
      dockerfile: Dockerfile
      args:
        SSHPASS: ${BUS_PASS}
        USER: ${BUS_USER}
        SERVER: ${BUS_SERVER}
    env_file:
      - .env
    ports:
      - "3000:5000"
    volumes:
      - ./socket:/app
        
  ###################-PG_ADMIN-##########################
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - db
    logging:
      driver: none