version: '3.5'

services:

  socket:
    container_name: socket
    restart: always
    build:
      context: ./socket/
      dockerfile: Dockerfile
      args:
        SSHPASS: ${BUS_PASS}
        USER: ${BUS_USER}
        SERVER: ${BUS_SERVER}
    env_file:
      - .env
    ports:
      - "3000:5000"
    volumes:
      - ./socket:/app

  # scrapper:
  #   container_name: scrapper
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   command: tail -f /dev/null
  #   volumes:
  #     - ./app:/app
   
  mariadb:
   container_name: mariadb
   image: bitnami/mariadb:latest
   volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
   ports:
        - "8000:3306"
   environment:
        - MARIADB_USER=mariadb
        - POSTGRESQL_DATABASE=tiendita
        - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_SKIP_TEST_DB=yes
        - MARIADB_PASSWORD=mariadb
   